import { UserRole } from "@prisma/client";
import { startOfDay, startOfMonth } from "date-fns";
import { requireGym, requirePageUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { AppShell } from "@/components/app-shell";
import { StatCard } from "@/components/stat-card";
import { GymActions } from "@/components/gym-actions";
import { QrActions } from "@/components/qr-actions";
import { AdminActions } from "@/components/admin-actions";

export const dynamic="force-dynamic";
export default async function GymDashboard(){const user=await requirePageUser([UserRole.GYM_OWNER,UserRole.ADMIN]);const gymId=requireGym(user);const now=new Date();const [members,plans,admins,qrGroups,todayVisits,monthVisits,denied,recent,activity]=await Promise.all([
db.memberProfile.findMany({where:{gymId},include:{user:true,memberships:{orderBy:{endDate:"desc"},take:1,include:{plan:true}},qrCodes:{orderBy:{createdAt:"desc"},take:1}},orderBy:{createdAt:"desc"},take:50}),db.membershipPlan.findMany({where:{gymId},orderBy:{createdAt:"desc"}}),db.user.findMany({where:{gymId,role:"ADMIN"},orderBy:{createdAt:"desc"}}),db.qRCode.groupBy({by:["status"],where:{gymId},_count:true}),db.accessLog.count({where:{gymId,result:"GRANTED",scannedAt:{gte:startOfDay(now)}}}),db.accessLog.count({where:{gymId,result:"GRANTED",scannedAt:{gte:startOfMonth(now)}}}),db.accessLog.count({where:{gymId,result:"DENIED",scannedAt:{gte:startOfDay(now)}}}),db.accessLog.findMany({where:{gymId},include:{member:{include:{user:{select:{fullName:true}}}},scannedBy:{select:{username:true}}},orderBy:{scannedAt:"desc"},take:10}),db.auditLog.findMany({where:{gymId},orderBy:{createdAt:"desc"},take:8})]);
const activeMembers=members.filter(m=>m.user.status==="ACTIVE"&&m.memberships.some(x=>x.status==="ACTIVE"&&x.endDate>now)).length;const qr=(s:string)=>qrGroups.find(x=>x.status===s)?._count??0;
return <AppShell user={user} section="dashboard"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-[var(--ember)]">{user.gym!.code} / Operations</p><h1 className="display mt-2 text-5xl sm:text-6xl">FLOOR CONTROL</h1><p className="mt-3 text-sm text-[var(--muted)]">{user.gym!.name} · {user.gym!.city}, {user.gym!.country}</p></div><GymActions plans={plans.map(p=>({id:p.id,name:p.name,durationDays:p.durationDays}))} members={members.map(m=>({id:m.id,fullName:m.user.fullName}))} owner={user.role==="GYM_OWNER"}/></div>
<section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total members" value={members.length} detail={`${activeMembers} active`} accent/><StatCard label="Today's visits" value={todayVisits} detail={`${monthVisits} this month`}/><StatCard label="Active QR" value={qr("ACTIVE")} detail={`${qr("BANNED")} banned · ${qr("REVOKED")} revoked`}/><StatCard label="Denied today" value={denied}/></section>
<section className="mt-12 grid gap-8 xl:grid-cols-[1.4fr_.6fr]"><div id="members"><p className="eyebrow text-[var(--muted)]">Roster</p><h2 className="display mt-2 text-3xl">MEMBERS</h2><div className="panel mt-4">
<div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[.65rem] uppercase tracking-widest text-[var(--muted)]"><tr>{["Member","ID","Membership","Valid until","QR"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{members.map(m=>{const ms=m.memberships[0],q=m.qrCodes[0];return <tr key={m.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4 font-black">{m.user.fullName}<div className="font-normal text-xs text-[var(--muted)]">@{m.user.username}</div></td><td className="p-4 font-mono text-xs">{m.memberNumber}</td><td className="p-4">{ms?.plan.name??"No plan"}</td><td className="p-4 whitespace-nowrap">{ms?ms.endDate.toLocaleDateString():"—"}</td><td className="p-4"><span className={`status ${q?.status==="ACTIVE"?"text-green-600":"text-[var(--muted)]"}`}>{q?.status??"NONE"}</span></td></tr>})}{!members.length&&<tr><td colSpan={5} className="p-10 text-center text-[var(--muted)]">No members yet. Register the first member to begin.</td></tr>}</tbody></table></div>
<div className="divide-y divide-[var(--line)] sm:hidden">{members.map(m=>{const ms=m.memberships[0],q=m.qrCodes[0];return <article key={m.id} className="p-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="break-words font-bold">{m.user.fullName}</p><p className="mt-1 break-all text-xs text-[var(--muted)]">@{m.user.username}</p></div><span className={`status shrink-0 ${q?.status==="ACTIVE"?"text-green-600":"text-[var(--muted)]"}`}>{q?.status??"NO QR"}</span></div><div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-3 text-sm"><div className="min-w-0"><p className="text-xs text-[var(--muted)]">Member ID</p><p className="mt-1 break-all font-mono text-xs">{m.memberNumber}</p></div><div className="min-w-0"><p className="text-xs text-[var(--muted)]">Plan</p><p className="mt-1 break-words">{ms?.plan.name??"No plan"}</p></div><div className="col-span-2"><p className="text-xs text-[var(--muted)]">Valid until</p><p className="mt-1">{ms?ms.endDate.toLocaleDateString():"—"}</p></div></div></article>})}{!members.length&&<p className="p-6 text-center text-sm text-[var(--muted)]">No members yet. Register the first member to begin.</p>}</div>
</div></div>
<div id="memberships"><p className="eyebrow text-[var(--muted)]">Products</p><h2 className="display mt-2 text-3xl">PLANS</h2><div className="mt-4 grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-1">{plans.map(p=><article className="panel min-w-0 p-4 sm:p-5" key={p.id}><div className="flex min-w-0 flex-col gap-3"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><b className="block break-words text-sm sm:text-base">{p.name}</b><p className="mt-1 text-xs text-[var(--muted)]">{p.durationDays} days</p></div><span className="status shrink-0">PLAN</span></div><div className="border-t border-[var(--line)] pt-3"><p className="text-xs text-[var(--muted)]">Membership price</p><p className="display mt-1 break-words text-2xl sm:text-3xl">{new Intl.NumberFormat("en-PH",{style:"currency",currency:p.currency}).format(p.priceCents/100)}</p></div></div></article>)}{!plans.length&&<div className="panel p-5 text-sm text-[var(--muted)]">Create a plan to assign memberships.</div>}</div></div></section>
<section className="mt-12"><p className="eyebrow text-[var(--muted)]">Credential control</p><h2 className="display mt-2 text-3xl">QR ACCESS</h2><div className="panel mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[.65rem] uppercase tracking-widest text-[var(--muted)]"><tr>{["Member","Status","Starts","Expires","Controls"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{members.filter(m=>m.qrCodes[0]).map(m=>{const q=m.qrCodes[0]!;return <tr key={q.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4 font-bold">{m.user.fullName}</td><td className="p-4"><span className={`status ${q.status==="ACTIVE"?"text-green-600":"text-[var(--ember)]"}`}>{q.status}</span></td><td className="p-4">{q.startDate.toLocaleDateString()}</td><td className="p-4">{q.expirationDate.toLocaleString()}</td><td className="p-4"><QrActions id={q.id} status={q.status}/></td></tr>})}</tbody></table></div></section>
<section id="activity" className="mt-12"><p className="eyebrow text-[var(--muted)]">Entrance decisions</p><h2 className="display mt-2 text-3xl">RECENT SCANS</h2><div className="panel mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[.65rem] uppercase tracking-widest text-[var(--muted)]"><tr>{["Entry","Member","Result","Reason","Scanner","Time"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{recent.map(x=><tr key={x.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4 font-mono text-xs">{x.entryNumber}</td><td className="p-4 font-bold">{x.member?.user.fullName??"Not disclosed"}</td><td className="p-4"><span className={`status ${x.result==="GRANTED"?"text-green-600":"text-red-600"}`}>{x.result}</span></td><td className="p-4">{x.reason}</td><td className="p-4">{x.scannedBy.username}</td><td className="p-4">{x.scannedAt.toLocaleString()}</td></tr>)}{!recent.length&&<tr><td colSpan={6} className="p-10 text-center text-[var(--muted)]">No entrance scans recorded.</td></tr>}</tbody></table></div></section>
{user.role==="GYM_OWNER"&&<section className="mt-12"><p className="eyebrow text-[var(--muted)]">Staff access</p><h2 className="display mt-2 text-3xl">ADMINISTRATORS</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{admins.map(a=><article className="panel p-4" key={a.id}><b>{a.fullName}</b><p className="mt-1 text-xs text-[var(--muted)]">@{a.username} · {a.email}</p><span className={`status mt-4 ${a.status==="ACTIVE"?"text-green-600":"text-[var(--ember)]"}`}>{a.status}</span><AdminActions id={a.id} status={a.status}/></article>)}</div></section>}
<section className="mt-12"><p className="eyebrow text-[var(--muted)]">Audit trail</p><h2 className="display mt-2 text-3xl">RECENT ACTIVITY</h2><div className="mt-4 grid gap-px border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2">{activity.map(a=><div className="bg-[var(--panel)] p-4" key={a.id}><b className="text-xs uppercase tracking-widest">{a.action.replaceAll("_"," ")}</b><p className="mt-2 text-sm">{a.description}</p><time className="mt-2 block text-xs text-[var(--muted)]">{a.createdAt.toLocaleString()}</time></div>)}</div></section></AppShell>}
