"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, CheckCircle2, Loader2 } from "lucide-react";
import { Brand } from "@/components/brand";

const fields=[
  ["gymName","Gym name","text",true],["slug","Gym URL slug","text",true],["gymType","Gym type","text",true],["description","Description","textarea",false],
  ["address","Street address","text",true],["city","City","text",true],["province","Province / State","text",false],["country","Country","text",true],
  ["contactNumber","Gym contact number","tel",true],["email","Gym email","email",true],["website","Website","url",false],["logoUrl","Logo URL","url",false],
  ["businessRegistration","Business registration information","textarea",true],["ownerFullName","Owner full name","text",true],["ownerUsername","Owner username","text",true],["ownerEmail","Owner email","email",true],["ownerPhone","Owner phone","tel",true],["password","Password (12+ characters)","password",true],["confirmPassword","Confirm password","password",true]
] as const;

export default function Apply(){const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const fd=new FormData(e.currentTarget);if(fd.get("password")!==fd.get("confirmPassword")){setError("Passwords do not match");return}setBusy(true);const body=Object.fromEntries(fd.entries());delete body.confirmPassword;const res=await fetch("/api/applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json();setBusy(false);if(!res.ok)setError(data.error??"Application could not be submitted");else setDone(true)}if(done)return <main className="grid min-h-screen place-items-center p-5"><div className="panel max-w-xl p-10 text-center"><CheckCircle2 className="mx-auto text-green-600" size={52}/><p className="eyebrow mt-7 text-green-700">Application received</p><h1 className="display mt-3 text-5xl">REVIEW QUEUED</h1><p className="mt-5 leading-7 text-[var(--muted)]">Your organization remains pending until a Platform Owner completes review. Your owner account activates only after approval.</p><Link href="/login" className="btn btn-dark mt-8">Return to sign in</Link></div></main>;
return <main className="min-h-screen"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><Brand/><Link href="/" className="flex items-center gap-2 text-xs font-black uppercase tracking-widest"><ArrowLeft size={14}/> Home</Link></header><section className="mx-auto max-w-6xl px-5 pb-20 pt-12"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><aside><p className="eyebrow text-[var(--ember)]">Gym onboarding</p><h1 className="display mt-4 text-6xl leading-[.88]">CLAIM YOUR<br/>OWN FLOOR.</h1><p className="mt-6 leading-7 text-[var(--muted)]">Submit complete business and owner information. The platform team reviews every application before any gym data or access is activated.</p><div className="mt-9 border-l-4 border-[var(--acid)] bg-[var(--ink)] p-5 text-sm leading-6 text-[var(--paper)]"><b className="eyebrow text-[var(--acid)]">What happens next</b><p className="mt-3 text-[#c8c2b8]">Pending → platform review → approval → isolated gym workspace and owner access.</p></div></aside><form onSubmit={submit} className="panel p-6 sm:p-9"><div className="mb-8 flex items-end justify-between border-b border-[var(--line)] pb-5"><div><p className="eyebrow text-[var(--muted)]">Application / 01</p><h2 className="display mt-2 text-3xl">ORGANIZATION DETAILS</h2></div><span className="display text-5xl text-[var(--line)]">A1</span></div><div className="grid gap-5 sm:grid-cols-2">{fields.map(([name,label,type,required])=><label key={name} className={type==="textarea"?"sm:col-span-2":""}><span className="label">{label}{required&&" *"}</span>{type==="textarea"?<textarea className="field min-h-24 resize-y" name={name} required={required}/>:<input className="field" name={name} type={type} required={required} minLength={type==="password"?12:undefined}/>}</label>)}</div>{error&&<p className="mt-6 border-l-4 border-red-600 bg-red-500/10 p-3 text-sm font-bold text-red-700" role="alert">{error}</p>}<div className="mt-8 flex flex-col-reverse items-center justify-between gap-4 border-t border-[var(--line)] pt-6 sm:flex-row"><p className="max-w-sm text-xs leading-5 text-[var(--muted)]">Submitting creates a pending application only. It does not grant immediate platform access.</p><button className="btn btn-primary shrink-0" disabled={busy}>{busy&&<Loader2 className="animate-spin" size={16}/>} Submit application</button></div></form></div></section></main>}
