import Link from "next/link";
import { ArrowRight, Check, Fingerprint, ScanLine, Shield, Users } from "lucide-react";
import { Brand } from "@/components/brand";
import { ThemeToggle } from "@/components/theme-toggle";

export default function Home(){return <div className="min-h-screen overflow-hidden"><header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Brand/><div className="flex items-center gap-2"><ThemeToggle/><Link className="btn btn-dark" href="/login">Sign in</Link></div></header>
<main><section className="relative mx-auto grid min-h-[690px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr]"><div className="grid-lines absolute -right-44 top-0 -z-10 h-[620px] w-[720px] rotate-6 opacity-60"/><div className="rise"><p className="eyebrow mb-5 text-[var(--ember)]">Multi-tenant gym operations / 2026</p><h1 className="display max-w-4xl text-[clamp(3.4rem,9vw,7.6rem)] leading-[.82]">ONE PLATFORM.<br/><span className="text-[var(--ember)]">EVERY GYM</span><br/>LOCKED DOWN.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[var(--muted)]">Membership, secure QR entry, attendance, and staff control—built for independent gyms that need their own space, not shared spreadsheets.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/apply" className="btn btn-primary">Apply for your gym <ArrowRight size={16}/></Link><Link href="/login" className="btn">Open dashboard</Link></div></div>
<div className="relative rise [animation-delay:150ms]"><div className="absolute -left-7 -top-7 h-28 w-28 bg-[var(--acid)]"/><div className="panel relative p-5 sm:p-7"><div className="flex items-center justify-between border-b border-[var(--line)] pb-5"><div><p className="eyebrow text-[var(--muted)]">Entrance terminal 01</p><h2 className="display mt-2 text-3xl">POWERFIT GYM</h2></div><span className="status text-green-600">Online</span></div><div className="my-8 grid place-items-center border border-dashed border-[var(--line)] bg-[var(--paper)] py-16"><div className="relative grid h-40 w-40 place-items-center border-2 border-[var(--ink)]"><span className="absolute -left-1 -top-1 h-8 w-8 border-l-4 border-t-4 border-[var(--ember)]"/><span className="absolute -bottom-1 -right-1 h-8 w-8 border-b-4 border-r-4 border-[var(--ember)]"/><ScanLine size={60} strokeWidth={1}/><span className="absolute bottom-5 eyebrow">Ready to scan</span></div></div><div className="grid grid-cols-3 gap-2 text-center"><div className="bg-[var(--ink)] p-3 text-[var(--paper)]"><b className="display text-2xl">148</b><p className="eyebrow mt-1 opacity-60">Visits</p></div><div className="bg-[var(--acid)] p-3 text-black"><b className="display text-2xl">97%</b><p className="eyebrow mt-1 opacity-60">Granted</p></div><div className="border border-[var(--line)] p-3"><b className="display text-2xl">05</b><p className="eyebrow mt-1 opacity-60">Denied</p></div></div></div></div></section>
<section className="bg-[var(--ink)] px-5 py-20 text-[var(--paper)]"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-3"><div><p className="eyebrow text-[var(--acid)]">Built for separation</p><h2 className="display mt-4 text-5xl leading-none">YOUR GYM.<br/>YOUR DATA.</h2></div>{[{icon:Shield,title:"Tenant walls",text:"Every operational query is scoped from the authenticated server session—not from client input."},{icon:Fingerprint,title:"Token security",text:"QRs contain random bearer tokens. Only one-way hashes are stored; passwords and member details stay out."},{icon:Users,title:"Clear authority",text:"Platform owner, gym owner, admin, and member permissions are enforced on every protected route."}].map(({icon:Icon,title,text})=><article key={title} className="border-l border-[#44423c] pl-6"><Icon className="text-[var(--ember)]"/><h3 className="display mt-8 text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[#aaa397]">{text}</p><div className="mt-6 flex gap-2 text-xs font-bold"><Check size={15} className="text-[var(--acid)]"/> SERVER VERIFIED</div></article>)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-24"><p className="eyebrow text-[var(--ember)]">Operational sequence</p><div className="mt-8 grid gap-px bg-[var(--line)] border border-[var(--line)] md:grid-cols-4">{[["01","Apply","Submit verified business and owner details."],["02","Approve","Platform review activates the isolated tenant."],["03","Operate","Create staff, members, plans, and access windows."],["04","Scan","Validate every rule and record every decision."]].map(([n,t,d])=><div className="bg-[var(--panel)] p-6" key={n}><span className="display text-5xl text-[var(--line)]">{n}</span><h3 className="display mt-8 text-2xl">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></section></main>
<footer className="border-t border-[var(--line)] px-5 py-7"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 text-xs font-bold uppercase tracking-widest"><span>IRONCLAD MULTI-GYM OS</span><span className="text-[var(--muted)]">Secure by tenancy. Clear by design.</span></div></footer></div>}

