"use client";
import { useState } from "react";
import { Plus, X } from "lucide-react";

type Plan={id:string;name:string;durationDays:number}; type Member={id:string;fullName:string};
function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 bg-black/60 p-3 sm:p-8" onMouseDown={onClose}><div className="ml-auto h-full max-w-xl overflow-y-auto bg-[var(--panel)] p-6 text-[var(--ink)] shadow-2xl sm:p-9" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-[var(--line)] pb-5"><h2 className="display text-3xl">{title}</h2><button onClick={onClose} aria-label="Close"><X/></button></div>{children}</div></div>}
async function send(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error??"Request failed");return data}
export function GymActions({plans,members,owner}:{plans:Plan[];members:Member[];owner:boolean}){const [mode,setMode]=useState<null|"member"|"plan"|"membership"|"admin"|"qr">(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const raw=Object.fromEntries(new FormData(e.currentTarget));try{if(mode==="plan")await send("/api/gym/plans",{...raw,priceCents:Math.round(Number(raw.price)*100),durationDays:Number(raw.durationDays)});if(mode==="membership")await send("/api/gym/memberships",{...raw,startDate:new Date()});if(mode==="admin")await send("/api/gym/admins",raw);if(mode==="member")await send("/api/gym/members",raw);if(mode==="qr"){const days=Number(raw.days);const startDate=new Date();const expirationDate=new Date(startDate.getTime()+days*86400000);const result=await send("/api/qr/create",{memberId:raw.memberId,startDate,expirationDate});const win=window.open();win?.document.write(`<title>Member QR</title><style>body{font-family:sans-serif;display:grid;place-items:center;height:100vh;margin:0}div{text-align:center}img{width:360px}</style><div><h1>Member Access QR</h1><img src="${result.imageDataUrl}"/><p>Valid until ${new Date(result.expirationDate).toLocaleString()}</p><button onclick="print()">Print</button></div>`)}location.reload()}catch(err){setError(err instanceof Error?err.message:"Request failed")}finally{setBusy(false)}}return <><div className="flex flex-wrap gap-2"><button className="btn btn-primary" onClick={()=>setMode("member")}><Plus size={15}/> Member</button><button className="btn" onClick={()=>setMode("plan")}><Plus size={15}/> Plan</button><button className="btn" onClick={()=>setMode("membership")}><Plus size={15}/> Membership</button><button className="btn" onClick={()=>setMode("qr")}><Plus size={15}/> QR access</button><button className="btn" onClick={()=>{const to=new Date();const from=new Date(to.getFullYear(),to.getMonth(),1);location.href=`/api/gym/reports?from=${from.toISOString()}&to=${to.toISOString()}`}}>Export report</button>{owner&&<button className="btn" onClick={()=>setMode("admin")}><Plus size={15}/> Admin</button>}</div>{mode&&<Drawer title={mode==="member"?"Register member":mode==="plan"?"Create plan":mode==="membership"?"Assign membership":mode==="admin"?"Add administrator":"Issue QR access"} onClose={()=>setMode(null)}><form onSubmit={submit} className="mt-7 space-y-4">
{mode==="member"&&<><Field name="fullName" label="Full name"/><Field name="username" label="Username"/><Field name="email" label="Email" type="email"/><Field name="phone" label="Phone"/><Field name="password" label="Temporary password (12+ characters)" type="password"/><label><span className="label">Membership plan</span><select className="field" name="planId" defaultValue=""><option value="">No plan yet</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {p.durationDays} days</option>)}</select></label></>}
{mode==="plan"&&<><Field name="name" label="Plan name"/><Field name="description" label="Description"/><Field name="price" label="Price" type="number"/><Field name="durationDays" label="Duration in days" type="number"/><input type="hidden" name="currency" value="PHP"/></>}
{mode==="membership"&&<><label><span className="label">Member</span><select className="field" name="memberId" required><option value="">Select member</option>{members.map(m=><option key={m.id} value={m.id}>{m.fullName}</option>)}</select></label><label><span className="label">Plan</span><select className="field" name="planId" required><option value="">Select plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {p.durationDays} days</option>)}</select></label></>}
{mode==="admin"&&<><Field name="fullName" label="Full name"/><Field name="username" label="Username"/><Field name="email" label="Email" type="email"/><Field name="phone" label="Phone"/><Field name="password" label="Temporary password (12+ characters)" type="password"/></>}
{mode==="qr"&&<><label><span className="label">Member</span><select className="field" name="memberId" required><option value="">Select a member</option>{members.map(m=><option key={m.id} value={m.id}>{m.fullName}</option>)}</select></label><label><span className="label">Access period</span><select className="field" name="days" defaultValue="30"><option value="1">1 day</option><option value="3">3 days</option><option value="7">7 days</option><option value="15">15 days</option><option value="30">30 days</option></select></label></>}
{error&&<p className="border-l-4 border-red-600 bg-red-500/10 p-3 text-sm font-bold text-red-700">{error}</p>}<button disabled={busy} className="btn btn-primary w-full">{busy?"Saving…":"Save and continue"}</button></form></Drawer>}</>}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <label><span className="label">{label}</span><input className="field" name={name} type={type} required={!["phone","description"].includes(name)} minLength={type==="password"?12:undefined}/></label>}
