"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, CheckCircle2, Keyboard, RotateCcw, XCircle } from "lucide-react";

type Result={allowed:boolean;reason:string;scannedAt:string;entryNumber:string;member:{fullName:string;username:string;memberNumber:string}|null;gym:string;membership:{plan:string;status:string}|null;qr:{status:string;expirationDate:string}|null;scannedBy:string};
export function QRScanner(){const [started,setStarted]=useState(false);const [manual,setManual]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState<Result|null>(null);const instance=useRef<{stop:()=>Promise<void>;clear:()=>void}|null>(null);const busyRef=useRef(false);
async function validate(token:string){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");try{const r=await fetch("/api/qr/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:token.trim()})});const data=await r.json();if(!r.ok)throw new Error(data.error??"Scan failed");setResult(data);if(instance.current)await instance.current.stop().catch(()=>{});}catch(e){setError(e instanceof Error?e.message:"Scan failed")}finally{busyRef.current=false;setBusy(false)}}
async function start(){setResult(null);setError("");setStarted(true);try{const {Html5Qrcode}=await import("html5-qrcode");const scanner=new Html5Qrcode("qr-reader");instance.current=scanner;await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:260,height:260}},decoded=>validate(decoded),()=>{});}catch(e){setError(e instanceof Error?e.message:"Camera could not start");setStarted(false)}}
useEffect(()=>()=>{instance.current?.stop().catch(()=>{})},[]);
if(result)return <div className={`overflow-hidden border-4 ${result.allowed?"border-green-500 bg-green-950":"border-red-500 bg-red-950"} text-white`}><div className={`grid min-h-56 place-items-center p-8 text-center ${result.allowed?"bg-green-500":"bg-red-500"}`}>{result.allowed?<CheckCircle2 size={76}/>:<XCircle size={76}/>}<h2 className="display mt-4 text-5xl">ACCESS {result.allowed?"GRANTED":"DENIED"}</h2><p className="mt-2 text-lg font-bold">{result.reason}</p></div><div className="grid gap-4 p-6 sm:grid-cols-2"><Info label="Member" value={result.member?.fullName??"Not disclosed"}/><Info label="Username" value={result.member?`@${result.member.username}`:"—"}/><Info label="Gym" value={result.gym}/><Info label="Membership" value={result.membership?`${result.membership.plan} · ${result.membership.status}`:"—"}/><Info label="QR status" value={result.qr?.status??"—"}/><Info label="Valid until" value={result.qr?new Date(result.qr.expirationDate).toLocaleString():"—"}/><Info label="Scanned" value={new Date(result.scannedAt).toLocaleString()}/><Info label="Scanned by" value={result.scannedBy}/></div><button className="btn m-6 bg-white text-black" onClick={()=>{setResult(null);setStarted(false)}}><RotateCcw size={16}/> Scan another</button></div>;
return <div className="panel overflow-hidden"><div className="border-b border-[var(--line)] p-6 text-center"><p className="eyebrow text-[var(--ember)]">Entrance terminal</p><h2 className="display mt-2 text-4xl">QR SCANNER</h2></div><div className="p-5 sm:p-8"><div className="mx-auto max-w-2xl border border-dashed border-[var(--line)] bg-black p-3"><div id="qr-reader" className="min-h-[360px] w-full overflow-hidden bg-[#090909] text-white">{!started&&<div className="grid min-h-[360px] place-items-center text-center"><div><Camera className="mx-auto text-[var(--acid)]" size={62} strokeWidth={1}/><p className="eyebrow mt-5 text-white">Camera is off</p><button className="btn btn-primary mt-5" onClick={start}>Start camera</button></div></div>}</div></div><p className="mx-auto mt-5 max-w-md text-center text-sm text-[var(--muted)]">Point the camera at the member&apos;s Ironclad QR code. Validation happens securely on the server.</p>{error&&<p className="mx-auto mt-4 max-w-2xl border-l-4 border-red-600 bg-red-500/10 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-6 text-center"><button className="btn" onClick={()=>setManual(!manual)}><Keyboard size={16}/> Enter QR manually</button></div>{manual&&<form className="mx-auto mt-5 flex max-w-2xl gap-2" onSubmit={e=>{e.preventDefault();validate(String(new FormData(e.currentTarget).get("token")))}}><input className="field" name="token" placeholder="Paste secure QR token" required minLength={20}/><button className="btn btn-primary" disabled={busy}>Validate</button></form>}</div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="border-b border-white/15 pb-3"><span className="eyebrow text-white/50">{label}</span><b className="mt-2 block">{value}</b></div>}

