import { UserRole } from "@prisma/client";
import { requirePageUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { AppShell } from "@/components/app-shell";
import { StatCard } from "@/components/stat-card";
import { ApplicationActions, GymStatusActions } from "@/components/platform-actions";
import { PlatformCreateGym } from "@/components/platform-create-gym";

export const dynamic="force-dynamic";
export default async function PlatformDashboard(){const user=await requirePageUser([UserRole.PLATFORM_OWNER]);const [gyms,pending,totalUsers,totalQr,totalScans,activity]=await Promise.all([
db.gym.findMany({include:{owner:{select:{fullName:true}},_count:{select:{memberProfiles:true}}},orderBy:{createdAt:"desc"}}),
db.gymApplication.findMany({where:{status:"PENDING"},orderBy:{createdAt:"asc"}}),db.user.groupBy({by:["role"],_count:true}),db.qRCode.count(),db.accessLog.count(),db.auditLog.findMany({orderBy:{createdAt:"desc"},take:12,include:{actor:{select:{username:true}},gym:{select:{name:true}}}})]);
const count=(role:string)=>totalUsers.find(x=>x.role===role)?._count??0;return <AppShell user={user} section="command"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-[var(--ember)]">Platform control / live</p><h1 className="display mt-2 text-5xl sm:text-6xl">NETWORK PULSE</h1></div><div className="flex items-center gap-3"><span className="status text-green-600">System operational</span><PlatformCreateGym/></div></div><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total gyms" value={gyms.length} detail={`${gyms.filter(g=>g.status==="ACTIVE").length} active`} accent/><StatCard label="Pending applications" value={pending.length}/><StatCard label="Total members" value={count("MEMBER")}/><StatCard label="QR scans" value={totalScans} detail={`${totalQr} codes issued`}/></section>
<section id="applications" className="mt-12"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow text-[var(--muted)]">Review queue</p><h2 className="display mt-2 text-3xl">GYM APPLICATIONS</h2></div><span className="display text-4xl text-[var(--line)]">{String(pending.length).padStart(2,"0")}</span></div><div className="panel overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[.65rem] uppercase tracking-widest text-[var(--muted)]"><tr>{["Gym / owner","Location","Type","Submitted","Actions"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{pending.map(a=><tr key={a.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4"><b>{a.gymName}</b><div className="text-xs text-[var(--muted)]">{a.ownerFullName} · {a.ownerEmail}</div></td><td className="p-4">{a.city}, {a.country}</td><td className="p-4">{a.gymType}</td><td className="p-4">{a.createdAt.toLocaleDateString()}</td><td className="p-4"><ApplicationActions id={a.id}/></td></tr>)}{!pending.length&&<tr><td colSpan={5} className="p-10 text-center text-[var(--muted)]">The review queue is clear.</td></tr>}</tbody></table></div></section>
<section id="gyms" className="mt-12"><p className="eyebrow text-[var(--muted)]">Tenant directory</p><h2 className="display mt-2 text-3xl">GYM NETWORK</h2><div className="mt-4 panel overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[.65rem] uppercase tracking-widest text-[var(--muted)]"><tr>{["Gym","Owner","Location","Members","Status","Action"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{gyms.map(g=><tr key={g.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4 font-black">{g.name}<div className="text-xs font-normal text-[var(--muted)]">{g.code}</div></td><td className="p-4">{g.owner?.fullName??"Unassigned"}</td><td className="p-4">{g.city}, {g.country}</td><td className="p-4">{g._count.memberProfiles}</td><td className="p-4"><span className={`status ${g.status==="ACTIVE"?"text-green-600":"text-[var(--ember)]"}`}>{g.status}</span></td><td className="p-4"><GymStatusActions id={g.id} status={g.status}/></td></tr>)}</tbody></table></div></section>
<section id="activity" className="mt-12"><p className="eyebrow text-[var(--muted)]">Platform trace</p><h2 className="display mt-2 text-3xl">RECENT AUDIT EVENTS</h2><div className="mt-4 grid gap-px border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2">{activity.map(a=><article className="bg-[var(--panel)] p-4" key={a.id}><div className="flex justify-between gap-3"><b className="text-xs uppercase tracking-wider">{a.action.replaceAll("_"," ")}</b><time className="text-xs text-[var(--muted)]">{a.createdAt.toLocaleString()}</time></div><p className="mt-2 text-sm">{a.description}</p><p className="mt-2 text-xs text-[var(--muted)]">{a.gym?.name??"Platform"} · {a.actor?.username??"System"}</p></article>)}</div></section></AppShell>}
